const cardTypes = {
  heart: "heart",
  spade: "spade",
  diamond: "diamond",
  club: "club",
};

export const deckOfCards = [
  {
    id: `1-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 1,
    deckNumber: 1,
  },
  {
    id: `2-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 2,
    deckNumber: 1,
  },
  {
    id: `3-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 3,
    deckNumber: 1,
  },
  {
    id: `4-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 4,
    deckNumber: 1,
  },
  {
    id: `5-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 5,
    deckNumber: 1,
  },
  {
    id: `6-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 6,
    deckNumber: 1,
  },
  {
    id: `7-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 7,
    deckNumber: 1,
  },
  {
    id: `8-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 8,
    deckNumber: 1,
  },
  {
    id: `9-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 9,
    deckNumber: 1,
  },
  {
    id: `10-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `11-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `12-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `13-${cardTypes.heart}`,
    type: cardTypes.heart,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `1-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 1,
    deckNumber: 1,
  },
  {
    id: `2-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 2,
    deckNumber: 1,
  },
  {
    id: `3-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 3,
    deckNumber: 1,
  },
  {
    id: `4-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 4,
    deckNumber: 1,
  },
  {
    id: `5-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 5,
    deckNumber: 1,
  },
  {
    id: `6-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 6,
    deckNumber: 1,
  },
  {
    id: `7-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 7,
    deckNumber: 1,
  },
  {
    id: `8-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 8,
    deckNumber: 1,
  },
  {
    id: `9-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 9,
    deckNumber: 1,
  },
  {
    id: `10-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `11-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `12-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `13-${cardTypes.spade}`,
    type: cardTypes.spade,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `1-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 1,
    deckNumber: 1,
  },
  {
    id: `2-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 2,
    deckNumber: 1,
  },
  {
    id: `3-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 3,
    deckNumber: 1,
  },
  {
    id: `4-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 4,
    deckNumber: 1,
  },
  {
    id: `5-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 5,
    deckNumber: 1,
  },
  {
    id: `6-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 6,
    deckNumber: 1,
  },
  {
    id: `7-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 7,
    deckNumber: 1,
  },
  {
    id: `8-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 8,
    deckNumber: 1,
  },
  {
    id: `9-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 9,
    deckNumber: 1,
  },
  {
    id: `10-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `11-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `12-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `13-${cardTypes.diamond}`,
    type: cardTypes.diamond,
    value: 10,
    deckNumber: 1,
  },
  { id: `1-${cardTypes.club}`, type: cardTypes.club, value: 1, deckNumber: 1 },
  { id: `2-${cardTypes.club}`, type: cardTypes.club, value: 2, deckNumber: 1 },
  { id: `3-${cardTypes.club}`, type: cardTypes.club, value: 3, deckNumber: 1 },
  { id: `4-${cardTypes.club}`, type: cardTypes.club, value: 4, deckNumber: 1 },
  { id: `5-${cardTypes.club}`, type: cardTypes.club, value: 5, deckNumber: 1 },
  { id: `6-${cardTypes.club}`, type: cardTypes.club, value: 6, deckNumber: 1 },
  { id: `7-${cardTypes.club}`, type: cardTypes.club, value: 7, deckNumber: 1 },
  { id: `8-${cardTypes.club}`, type: cardTypes.club, value: 8, deckNumber: 1 },
  { id: `9-${cardTypes.club}`, type: cardTypes.club, value: 9, deckNumber: 1 },
  {
    id: `10-${cardTypes.club}`,
    type: cardTypes.club,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `11-${cardTypes.club}`,
    type: cardTypes.club,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `12-${cardTypes.club}`,
    type: cardTypes.club,
    value: 10,
    deckNumber: 1,
  },
  {
    id: `13-${cardTypes.club}`,
    type: cardTypes.club,
    value: 10,
    deckNumber: 1,
  },
];

export const participants = {
  PLAYER_1: "Player1",
  DEALER: "Dealer",
};
