const cardTypes = {
  heart: "heart",
  spade: "spade",
  diamond: "diamond",
  club: "club",
};

export const deckOfCards = [
  { id: `1-${cardTypes.heart}-1`, type: cardTypes.heart, value: 1 },
  { id: `2-${cardTypes.heart}-1`, type: cardTypes.heart, value: 2 },
  { id: `3-${cardTypes.heart}-1`, type: cardTypes.heart, value: 3 },
  { id: `4-${cardTypes.heart}-1`, type: cardTypes.heart, value: 4 },
  { id: `5-${cardTypes.heart}-1`, type: cardTypes.heart, value: 5 },
  { id: `6-${cardTypes.heart}-1`, type: cardTypes.heart, value: 6 },
  { id: `7-${cardTypes.heart}-1`, type: cardTypes.heart, value: 7 },
  { id: `8-${cardTypes.heart}-1`, type: cardTypes.heart, value: 8 },
  { id: `9-${cardTypes.heart}-1`, type: cardTypes.heart, value: 9 },
  { id: `10-${cardTypes.heart}-1`, type: cardTypes.heart, value: 10 },
  { id: `11-${cardTypes.heart}-1`, type: cardTypes.heart, value: 10 },
  { id: `12-${cardTypes.heart}-1`, type: cardTypes.heart, value: 10 },
  { id: `13-${cardTypes.heart}-1`, type: cardTypes.heart, value: 10 },
  { id: `1-${cardTypes.spade}-1`, type: cardTypes.spade, value: 1 },
  { id: `2-${cardTypes.spade}-1`, type: cardTypes.spade, value: 2 },
  { id: `3-${cardTypes.spade}-1`, type: cardTypes.spade, value: 3 },
  { id: `4-${cardTypes.spade}-1`, type: cardTypes.spade, value: 4 },
  { id: `5-${cardTypes.spade}-1`, type: cardTypes.spade, value: 5 },
  { id: `6-${cardTypes.spade}-1`, type: cardTypes.spade, value: 6 },
  { id: `7-${cardTypes.spade}-1`, type: cardTypes.spade, value: 7 },
  { id: `8-${cardTypes.spade}-1`, type: cardTypes.spade, value: 8 },
  { id: `9-${cardTypes.spade}-1`, type: cardTypes.spade, value: 9 },
  { id: `10-${cardTypes.spade}-1`, type: cardTypes.spade, value: 10 },
  { id: `11-${cardTypes.spade}-1`, type: cardTypes.spade, value: 10 },
  { id: `12-${cardTypes.spade}-1`, type: cardTypes.spade, value: 10 },
  { id: `13-${cardTypes.spade}-1`, type: cardTypes.spade, value: 10 },
  { id: `1-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 1 },
  { id: `2-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 2 },
  { id: `3-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 3 },
  { id: `4-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 4 },
  { id: `5-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 5 },
  { id: `6-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 6 },
  { id: `7-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 7 },
  { id: `8-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 8 },
  { id: `9-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 9 },
  { id: `10-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 10 },
  { id: `11-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 10 },
  { id: `12-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 10 },
  { id: `13-${cardTypes.diamond}-1`, type: cardTypes.diamond, value: 10 },
  { id: `1-${cardTypes.club}-1`, type: cardTypes.club, value: 1 },
  { id: `2-${cardTypes.club}-1`, type: cardTypes.club, value: 2 },
  { id: `3-${cardTypes.club}-1`, type: cardTypes.club, value: 3 },
  { id: `4-${cardTypes.club}-1`, type: cardTypes.club, value: 4 },
  { id: `5-${cardTypes.club}-1`, type: cardTypes.club, value: 5 },
  { id: `6-${cardTypes.club}-1`, type: cardTypes.club, value: 6 },
  { id: `7-${cardTypes.club}-1`, type: cardTypes.club, value: 7 },
  { id: `8-${cardTypes.club}-1`, type: cardTypes.club, value: 8 },
  { id: `9-${cardTypes.club}-1`, type: cardTypes.club, value: 9 },
  { id: `10-${cardTypes.club}-1`, type: cardTypes.club, value: 10 },
  { id: `11-${cardTypes.club}-1`, type: cardTypes.club, value: 10 },
  { id: `12-${cardTypes.club}-1`, type: cardTypes.club, value: 10 },
  { id: `13-${cardTypes.club}-1`, type: cardTypes.club, value: 10 },
];

export const participants = {
  PLAYER_1: "Player 1",
  DEALER: "Dealer",
};
